name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: windows-latest  # Cambia el entorno de ejecuci칩n a Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Deshabilitar shallow clones para una mejor relevancia del an치lisis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: C:\\Users\\runneradmin\\.sonar\\cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener informaci칩n de PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de autenticaci칩n para SonarCloud

